// Copyright (c) 2026 Computer Vision Center (CVC) at the Universitat Autonoma
// de Barcelona (UAB).
//
// This work is licensed under the terms of the MIT license.
// For a copy, see <https://opensource.org/licenses/MIT>.

#pragma once

#include "carla/rpc/Location.h"
#include "carla/sensor/data/SemanticLidarData.h"

#include <cstdint>
#include <vector>

namespace carla {

namespace ros2 {
  class ROS2;
}

namespace sensor {

namespace s11n {
  class LidarSerializer;
  class LidarHeaderView;
}

namespace data {

  /// Helper class to store and serialize the data generated by a Lidar.
  ///
  /// The header of a Lidar measurement consists of an array of uint32_t's in
  /// the following layout
  ///
  ///    {
  ///      Horizontal angle (float),
  ///      Channel count,
  ///      Point count of channel 0,
  ///      ...
  ///      Point count of channel n,
  ///    }
  ///
  /// The points are stored in an array of floats
  ///
  ///    {
  ///      X0, Y0, Z0, I0
  ///      ...
  ///      Xn, Yn, Zn, In
  ///    }
  ///

  class LidarDetection {
    public:
      geom::Location point;
      float intensity;

      LidarDetection() :
          point(0.0f, 0.0f, 0.0f), intensity{0.0f} { }
      LidarDetection(float x, float y, float z, float intensity) :
          point(x, y, z), intensity{intensity} { }
      LidarDetection(geom::Location p, float intensity) :
          point(p), intensity{intensity} { }

      void WritePlyHeaderInfo(std::ostream& out) const{
        out << "property float32 x\n" \
          "property float32 y\n" \
          "property float32 z\n" \
          "property float32 I";
      }

      void WriteDetection(std::ostream& out) const{
        out << point.x << ' ' << point.y << ' ' << point.z << ' ' << intensity;
      }
  };

  /// Per-point companion data for the opt-in extended (PointXYZIRCAEDT) lidar
  /// layout, stored parallel to LidarData::_points (same point order, 1:1).
  ///
  /// LidarDetection itself is deliberately NOT widened: LidarMeasurement
  /// reinterprets the serialized _points buffer as Array<LidarDetection> under
  /// a static_assert(sizeof(LidarDetection) == 4*sizeof(float)) (see
  /// LidarMeasurement.h), and the recorder/replay format is that same 16-byte
  /// flat stream. Growing LidarDetection would break both. The extra fields the
  /// extended ROS 2 layout needs — that are not already x/y/z/intensity — live
  /// here instead and are only ever consumed by ROS2::ProcessDataFromLidar's
  /// extended branch. return_type is a single-return-model constant (0) carried
  /// for symmetry; time_stamp is frame-level and set at pack time, so it is not
  /// stored per point here. Angles are in radians (tier4 convention), distance
  /// in metres.
  struct LidarDetectionExtra {
    uint8_t  return_type = 0u;
    uint16_t channel = 0u;
    float    azimuth = 0.0f;
    float    elevation = 0.0f;
    float    distance = 0.0f;
  };

  class LidarData : public SemanticLidarData{

  public:
    explicit LidarData(uint32_t ChannelCount = 0u)
      : SemanticLidarData(ChannelCount) {
    }

    LidarData &operator=(LidarData &&) = default;

    ~LidarData() = default;

    virtual void ResetMemory(std::vector<uint32_t> points_per_channel) {
      DEBUG_ASSERT(GetChannelCount() >= points_per_channel.size());
      std::memset(_header.data() + Index::SIZE, 0, sizeof(uint32_t) * GetChannelCount());

      uint32_t total_points = static_cast<uint32_t>(
          std::accumulate(points_per_channel.begin(), points_per_channel.end(), 0));

      _points.clear();
      _points.reserve(total_points * 4);

      // The extended companion buffer is only populated when the opt-in layout
      // is active; keep it empty (and allocation-free) otherwise so the default
      // path pays nothing.
      _points_extra.clear();
      if (_extended) {
        _points_extra.reserve(total_points);
      }
    }

    void WritePointSync(LidarDetection &detection) {
      _points.emplace_back(detection.point.x);
      _points.emplace_back(detection.point.y);
      _points.emplace_back(detection.point.z);
      _points.emplace_back(detection.intensity);
    }

    virtual void WritePointSync(SemanticLidarDetection &detection) {
      (void) detection;
      DEBUG_ASSERT(false);
    }

    /// Opt-in extended (PointXYZIRCAEDT) layout toggle. Set once at sensor Set()
    /// time from the ros2_extended_lidar blueprint attribute. When false,
    /// WritePointExtra is never called and _points_extra stays empty.
    void SetExtended(bool extended) { _extended = extended; }
    bool IsExtended() const { return _extended; }

    /// Append the extra fields for the point most recently WritePointSync'd, in
    /// lockstep with _points. Callers must invoke this exactly once per kept
    /// detection (after the drop-off postprocess) when IsExtended() is true.
    void WritePointExtra(uint8_t return_type, uint16_t channel,
                         float azimuth, float elevation, float distance) {
      _points_extra.push_back(
          LidarDetectionExtra{return_type, channel, azimuth, elevation, distance});
    }

  private:
    std::vector<float> _points;

    // Extended-layout state. _points_extra[i] is the companion of the point at
    // _points[i*4 .. i*4+3]; both are filled in the same order by the sensor's
    // ComputeAndSaveDetections and consumed together by ProcessDataFromLidar.
    bool _extended = false;
    std::vector<LidarDetectionExtra> _points_extra;

    friend class s11n::LidarSerializer;
    friend class s11n::LidarHeaderView;
    friend class carla::ros2::ROS2;
  };

} // namespace s11n
} // namespace sensor
} // namespace carla
