name: Ubicloud-PR

on:
  pull_request:
    branches:
      - ue5-dev
    types: [opened, synchronize, reopened]

concurrency:
  group: ubicloud-pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build:
    name: Ubuntu ${{ matrix.ubuntu-version }}
    strategy:
      fail-fast: false
      matrix:
        ubuntu-version: ["22.04"]
    uses: ./.github/workflows/_ci-ubicloud.yml
    with:
      ubuntu-version: ${{ matrix.ubuntu-version }}
